apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: apps
  labels:
    app.kubernetes.io/name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: http-vol # must match local name
      mountPath:  /usr/local/apache2/htdocs/ # location to drop files from config


  volumes:
  - name: http-vol # local name
    configMap:
      name: http-index # must match config map name

